In [1]:
import pandas as pd
import numpy as np
import math
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression as LR

In [11]:
root_dir = '/Users/kessapassa/OneDrive/research_log/20181227/Interpolated_3D/'

In [12]:
dir_list = ['4_6', '5_5', '6_4']
seed_list = [str(123 + i) for i in range(2)]
csv_list = ['census', 'mobile']

In [13]:
csv_array = {}
for _dir in dir_list:
    csv_array[_dir] = {}
    for _seed in seed_list:
        csv_array[_dir][_seed] = {}
        for _csv in csv_list:
            df = pd.read_csv(root_dir + _dir + 'seed' + _seed + '_' + _csv + '.csv',
                                                index_col=0,
                                                encoding='Shift_JISx0213')
            csv_array[_dir][_seed][_csv] = df

In [14]:
csv_array['6_4']['123']['census']

      3600   7200  10800  18000
0      0.0    0.0    0.0    0.0
1      8.0    0.0    0.0    0.0
2     28.0    0.0    0.0    0.0
3      0.0    0.0    0.0    0.0
4      0.0    0.0    0.0    0.0
5      0.0    0.0    0.0    0.0
6    188.0   16.0    0.0    3.0
7      5.0    0.0    0.0    0.0
8    123.0    6.0    0.0    0.0
9     35.0    2.0    0.0    0.0
10     0.0    0.0    0.0    0.0
11     0.0    0.0    0.0    0.0
12    33.0    7.0    0.0    0.0
13   137.0   11.0    0.0    1.0
14   656.0   30.0    2.0    3.0
15   555.0   32.0    2.0    1.0
16     9.0    0.0    0.0    0.0
17     8.0    2.0    0.0    0.0
18    22.0    2.0    0.0    0.0
19    24.0    4.0    0.0    0.0
20   101.0    6.0    0.0    0.0
21  2886.0  211.0    5.0    2.0
22   832.0   64.0    0.0    0.0
23    26.0    2.0    0.0    0.0
24     3.0    0.0    0.0    0.0
25    54.0    4.0    0.0    0.0
26    80.0    4.0    0.0    0.0
27  2437.0  145.0    4.0    0.0
28  1842.0  123.0    3.0    0.0
29     1.0    0.0    0.0    0.0
30     0.0    0.0    0.0    0.0
31    45.0    0.0    0.0    0.0
32    71.0    3.0    0.0    0.0
33   497.0   50.0    2.0    0.0
34   318.0   29.0    2.0    0.0
35   161.0   21.0    2.0    0.0